"""add is_active field to user model

Revision ID: a067aae8a527
Revises: 5c7cb3104770
Create Date: 2025-06-07 23:57:33.784199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a067aae8a527'
down_revision = '5c7cb3104770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the default constraint first, then drop the column
    op.execute("ALTER TABLE users DROP CONSTRAINT DF__users__is_active__62108194")
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
