"""add example migration

Revision ID: 5c7cb3104770
Revises: cabcbd0d8153
Create Date: 2025-06-07 23:56:28.866920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7cb3104770'
down_revision = 'cabcbd0d8153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__tasks__task_auth__60283922', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['task_author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('FK__tasks__task_auth__60283922', 'tasks', 'users', ['task_author_id'], ['id'])
    # ### end Alembic commands ###
